UPDATE `script_texts` SET `content_loc4` =  '谁敢打扰阿鲁高之子？' WHERE `entry` = -1033013;
UPDATE `script_texts` SET `content_loc4` =  '你也要听从我的命令。' WHERE `entry` = -1033017;
UPDATE `script_texts` SET `content_loc4` =  '又干掉了一个蠢货！' WHERE `entry` = -1033018;
UPDATE `script_texts` SET `content_loc4` =  '释放你的怒气吧！' WHERE `entry` = -1033019;
UPDATE `script_texts` SET `content_loc4` =  '你们几个，去看看那边是怎么回事！' WHERE `entry` = -1036000;
UPDATE `script_texts` SET `content_loc4` =  '我们被攻击了，把他们都干掉。 ' WHERE `entry` = -1036001;
UPDATE `script_texts` SET `content_loc4` =  '你们这些旱鸭子比我想象得要厉害多了，看来我要认真一些了。' WHERE `entry` = -1036002;
UPDATE `script_texts` SET `content_loc4` =  '嘎，我要发怒了！' WHERE `entry` = -1036003;
UPDATE `script_texts` SET `content_loc4` =  '我终于醒来了！' WHERE `entry` = -1043013;
UPDATE `script_texts` SET `content_loc4` =  '谁敢唤醒阿扎达斯？谁敢冒犯造物之神？ ' WHERE `entry` = -1070001;
UPDATE `script_texts` SET `content_loc4` =  '苏醒吧，我的奴仆……为保护圆盘而战！' WHERE `entry` = -1070002;
UPDATE `script_texts` SET `content_loc4` =  '到我这来，兄弟们……为造物之神而战！' WHERE `entry` = -1070003;
UPDATE `script_texts` SET `content_loc4` =  '可笑的凡人。 ' WHERE `entry` = -1070004;
UPDATE `script_texts` SET `content_loc4` =  '篡位者，诺莫瑞根是我的！' WHERE `entry` = -1090024;
UPDATE `script_texts` SET `content_loc4` =  '我的机器人才是未来，你们都得死！ ' WHERE `entry` = -1090025;
UPDATE `script_texts` SET `content_loc4` =  '炸药，更多的炸药，我要更多的炸药！' WHERE `entry` = -1090026;
UPDATE `script_texts` SET `content_loc4` =  '去死吧！ ' WHERE `entry` = -1090027;
UPDATE `script_texts` SET `content_loc4` =  '防护盾消失了，起来吧，阿塔莱，起来吧！ ' WHERE `entry` = -1109005;
UPDATE `script_texts` SET `content_loc4` =  '哈卡复活了！' WHERE `entry` = -1109006;
UPDATE `script_texts` SET `content_loc4` =  '我要品尝生命的鲜血。' WHERE `entry` = -1109007;
UPDATE `script_texts` SET `content_loc4` =  '我离你们的世界越来越近了。' WHERE `entry` = -1109008;
UPDATE `script_texts` SET `content_loc4` =  '我来了！' WHERE `entry` = -1109009;
UPDATE `script_texts` SET `content_loc4` =  '我在这！' WHERE `entry` = -1109010;
UPDATE `script_texts` SET `content_loc4` =  '给我来一次真正的挑战吧！' WHERE `entry` = -1189000;
UPDATE `script_texts` SET `content_loc4` =  '光明之刃！ ' WHERE `entry` = -1189001;
UPDATE `script_texts` SET `content_loc4` =  '圣光，赐予我力量吧！' WHERE `entry` = -1189002;
UPDATE `script_texts` SET `content_loc4` =  '哈，你们就这点本事吗？ ' WHERE `entry` = -1189003;
UPDATE `script_texts` SET `content_loc4` =  '' WHERE `entry` = -1189004;
UPDATE `script_texts` SET `content_loc4` =  '异教徒！……净化他们！ ' WHERE `entry` = -1189005;
UPDATE `script_texts` SET `content_loc4` =  '真可笑。' WHERE `entry` = -1189006;
UPDATE `script_texts` SET `content_loc4` =  '为你而战，我的女士！' WHERE `entry` = -1189007;
UPDATE `script_texts` SET `content_loc4` =  '莫格莱尼你死了吗？你们要为此付出代价！ ' WHERE `entry` = -1189008;
UPDATE `script_texts` SET `content_loc4` =  '圣光会审判你们的！' WHERE `entry` = -1189009;
UPDATE `script_texts` SET `content_loc4` =  '复活吧，我的勇士！' WHERE `entry` = -1189010;
UPDATE `script_texts` SET `content_loc4` =  '你不能玷污这些圣迹！' WHERE `entry` = -1189019;
UPDATE `script_texts` SET `content_loc4` =  '让正义的火焰吞噬你们吧！' WHERE `entry` = -1189020;
UPDATE `script_texts` SET `content_loc4` =  '啊，沙漠会将你吞噬！' WHERE `entry` = -1209001;
UPDATE `script_texts` SET `content_loc4` =  '死吧！ ' WHERE `entry` = -1209002;
UPDATE `script_texts` SET `content_loc4` =  '让复仇的毒蛇吞噬你们吧！ ' WHERE `entry` = -1309000;
UPDATE `script_texts` SET `content_loc4` =  '希里克，赐予我复仇的翅膀。' WHERE `entry` = -1309002;
UPDATE `script_texts` SET `content_loc4` =  '必然的结局……死亡，诅咒你，哈卡，诅咒你！ ' WHERE `entry` = -1309004;
UPDATE `script_texts` SET `content_loc4` =  '用你的蛛网将我围绕，沙德拉女神，释放你致命的毒液吧！' WHERE `entry` = -1309005;
UPDATE `script_texts` SET `content_loc4` =  '我祝福你，凡人，你给了我自由，哈卡再也无法控制我了……' WHERE `entry` = -1309008;
UPDATE `script_texts` SET `content_loc4` =  '希瓦拉尔，让我感受你的愤怒吧！' WHERE `entry` = -1309009;
UPDATE `script_texts` SET `content_loc4` =  '哈卡再也不能束缚我了，我终于可以安息了！' WHERE `entry` = -1309010;
UPDATE `script_texts` SET `content_loc4` =  '贝瑟克，你的祭祀在召唤你的力量。' WHERE `entry` = -1309011;
UPDATE `script_texts` SET `content_loc4` =  '我终于摆脱了夺灵者的束缚。' WHERE `entry` = -1309013;
UPDATE `script_texts` SET `content_loc4` =  '朋友，欢迎参加这场盛宴。来吧，狂欢至死吧！ ' WHERE `entry` = -1309014;
UPDATE `script_texts` SET `content_loc4` =  '让哈卡吞噬你的灵魂吧！ ' WHERE `entry` = -1309015;
UPDATE `script_texts` SET `content_loc4` =  '骄傲会将你送上绝路。来吧，凡人，品尝夺灵者的愤怒吧！ ' WHERE `entry` = -1309020;
UPDATE `script_texts` SET `content_loc4` =  '可笑的凡人!在烈焰之子面前灰飞烟灭吧！' WHERE `entry` = -1409003;
UPDATE `script_texts` SET `content_loc4` =  '守护符文被摧毁了！兄弟们，杀掉这些入侵者！' WHERE `entry` = -1409004;
UPDATE `script_texts` SET `content_loc4` =  '尘归尘土归土！' WHERE `entry` = -1409005;
UPDATE `script_texts` SET `content_loc4` =  '燃烧吧凡人，为你们的罪恶付出代价吧。' WHERE `entry` = -1409006;
UPDATE `script_texts` SET `content_loc4` =  '不，不可能，等一下，我投降，我投降，你们要不顾一切的揭开烈焰之子的秘密，你们会为这鲁莽的行为付出巨大的代价，我将召唤这位真正的主人，让你们直接面对他无尽的愤怒，你们渺小的生命即将完结。' WHERE `entry` = -1409007;
UPDATE `script_texts` SET `content_loc4` =  '拉格纳罗斯，火焰之王！他比这个世界本身还要古老，在他面前屈服吧！在你们的末日面前屈服吧!' WHERE `entry` = -1409008;
UPDATE `script_texts` SET `content_loc4` =  '你为什么要唤醒我！埃克索图斯, 为什么要打扰我！' WHERE `entry` = -1409009;
UPDATE `script_texts` SET `content_loc4` =  '是因为这些入侵者，我的主人!他们闯入了您的圣殿，想要窃取您的秘密！' WHERE `entry` = -1409010;
UPDATE `script_texts` SET `content_loc4` =  '蠢货，你让这些不值一击的虫子进入这个神圣的地方，现在你还将他们引了到我这里来，你太让我失望了！埃克索图斯你太让我失望了！' WHERE `entry` = -1409011;
UPDATE `script_texts` SET `content_loc4` =  '现在轮到你们了，你们愚蠢的追信拉格纳罗斯的力量，现在你们即将亲眼见到它。' WHERE `entry` = -1409012;
UPDATE `script_texts` SET `content_loc4` =  '出现吧我的奴仆！保卫你们的主人！' WHERE `entry` = -1409013;
UPDATE `script_texts` SET `content_loc4` =  '我是不可战胜的！出现吧火焰的奴仆！你们的主人在召唤你们！' WHERE `entry` = -1409014;
UPDATE `script_texts` SET `content_loc4` =  '让火焰净化一切！' WHERE `entry` = -1409015;
UPDATE `script_texts` SET `content_loc4` =  '感受萨弗隆的烈焰吧！' WHERE `entry` = -1409016;
UPDATE `script_texts` SET `content_loc4` =  '去死吧！' WHERE `entry` = -1409017;
UPDATE `script_texts` SET `content_loc4` =  '我已经失去耐心了，你们都去死吧！' WHERE `entry` = -1409018;
UPDATE `script_texts` SET `content_loc4` =  '你以为你们赢了？看来要你们还需要更多痛苦的教训！' WHERE `entry` = -1409019;
UPDATE `script_texts` SET `content_loc4` =  '我的火焰，请不要夺走我的火焰……' WHERE `entry` = -1409022;
UPDATE `script_texts` SET `content_loc4` =  '很好， $N。' WHERE `entry` = -1409023;
UPDATE `script_texts` SET `content_loc4` =  '你们怎么进来的？你们这些凡人不应该来这里，我要把你们全部杀掉！' WHERE `entry` = -1469000;
UPDATE `script_texts` SET `content_loc4` =  '你们很聪明，凡人！但是我不会那么轻易的离开我的圣地！' WHERE `entry` = -1469001;
UPDATE `script_texts` SET `content_loc4` =  '%s因皮肤闪着微光而惊讶退缩。' WHERE `entry` = -1469003;
UPDATE `script_texts` SET `content_loc4` =  '比赛开始！ ' WHERE `entry` = -1469005;
UPDATE `script_texts` SET `content_loc4` =  '啊，英雄们，你们都会坚持不懈的，是不是？你们这群凡人想要与我的力量相抗衡，那么你们就要付出代价。现在他将为我而战，他的任务就是干掉你们。醒来吧，小红龙，毁灭他们！' WHERE `entry` = -1469006;
UPDATE `script_texts` SET `content_loc4` =  '干得好，我的手下，凡人的http://121.49.81.111:8080/0and1Register/勇气已经开始消退了，现在，让我们看看他们如何应对黑石塔真正主人的力量。' WHERE `entry` = -1469007;
UPDATE `script_texts` SET `content_loc4` =  '够了，现在你们将感受到我与生俱来的力量……大地的愤怒！' WHERE `entry` = -1469008;
UPDATE `script_texts` SET `content_loc4` =  '燃烧吧，你们这些悲惨的家伙，燃烧吧！' WHERE `entry` = -1469009;
UPDATE `script_texts` SET `content_loc4` =  '不可能！出现吧，我的仆人，再次为你们的主人效力！' WHERE `entry` = -1469010;
UPDATE `script_texts` SET `content_loc4` =  '$N，没用的废物，你的朋友不久之后就会去找你的。 ' WHERE `entry` = -1469011;
UPDATE `script_texts` SET `content_loc4` =  '这不可能，我是这里的主人，你们这些凡人对我来说一无是处……听到了没有？一无是处！' WHERE `entry` = -1469012;
UPDATE `script_texts` SET `content_loc4` =  '你要为强迫我这么做而付出代价！' WHERE `entry` = -1469022;
UPDATE `script_texts` SET `content_loc4` =  '蠢货，这些蛋比你认为的要珍贵得多！' WHERE `entry` = -1469023;
UPDATE `script_texts` SET `content_loc4` =  '不，住手，我要你的头颅来弥补你的罪行！' WHERE `entry` = -1469024;
UPDATE `script_texts` SET `content_loc4` =  '如果我要落入地狱，那么你们这些凡人也要与我同去。' WHERE `entry` = -1469025;
UPDATE `script_texts` SET `content_loc4` =  '太晚了，朋友们，奈法里奥斯的堕落力量已经生效，我无法……控制自己。' WHERE `entry` = -1469026;
UPDATE `script_texts` SET `content_loc4` =  '求求你们，快跑吧，在我丧失所有理智之前快逃命吧，黑色的火焰在我的心中燃烧，我必须要释放他！ ' WHERE `entry` = -1469027;
UPDATE `script_texts` SET `content_loc4` =  '火焰、死亡、毁灭，你们这些凡人，让奈法里奥斯大人的力量……不，我要抗争，阿莱克斯塔萨，帮帮我，我必须抗争到底！' WHERE `entry` = -1469028;
UPDATE `script_texts` SET `content_loc4` =  '奈法里奥斯的仇恨让我变得空前的强大，赶快快跑吧，凡人，黑石之王的怒气涌动在我的血脉中！' WHERE `entry` = -1469029;
UPDATE `script_texts` SET `content_loc4` =  '原谅我，$N！你的死亡让我的失败更加沉重。' WHERE `entry` = -1469030;
UPDATE `script_texts` SET `content_loc4` =  '我们复仇的时刻到了，让敌人的内心，被黑暗吞噬吧！' WHERE `entry` = -1509005;
UPDATE `script_texts` SET `content_loc4` =  '我们不用在待在这座石墙里面了，我们很快就能报仇了！在我们的怒火面前，就连那些龙，也会战栗！' WHERE `entry` = -1509006;
UPDATE `script_texts` SET `content_loc4` =  '让敌人胆战心惊吧！让他们在恐惧中死去！' WHERE `entry` = -1509007;
UPDATE `script_texts` SET `content_loc4` =  '鹿盔将会呜咽着哀求我饶他一命，就像他那懦弱的儿子一样。一千年来的屈辱，会在今天洗清！' WHERE `entry` = -1509008;
UPDATE `script_texts` SET `content_loc4` =  '范达尔，你的死期到了，藏到翡翠梦境中去吧，祈祷我们永远找不到你。' WHERE `entry` = -1509009;
UPDATE `script_texts` SET `content_loc4` =  '无礼的蠢货！我会亲自要了你们的命！' WHERE `entry` = -1509010;
UPDATE `script_texts` SET `content_loc4` =  '进攻！让他们付出惨痛的代价！' WHERE `entry` = -1509011;
UPDATE `script_texts` SET `content_loc4` =  '碾碎他们！把他们干掉！' WHERE `entry` = -1509012;
UPDATE `script_texts` SET `content_loc4` =  '还犹豫什么？干掉他们！' WHERE `entry` = -1509013;
UPDATE `script_texts` SET `content_loc4` =  '战士们！军官们！继续战斗！' WHERE `entry` = -1509014;
UPDATE `script_texts` SET `content_loc4` =  '$N，你不值得我浪费时间！' WHERE `entry` = -1509015;
UPDATE `script_texts` SET `content_loc4` =  '拿命来！' WHERE `entry` = -1509016;
UPDATE `script_texts` SET `content_loc4` =  '不久你们就会知道干预的代价了！凡人…主人几乎完全...当他出现，你们的世界将被终结！' WHERE `entry` = -1509017;
UPDATE `script_texts` SET `content_loc4` =  '我又恢复了活力！' WHERE `entry` = -1509018;
UPDATE `script_texts` SET `content_loc4` =  '我的力量恢复了！' WHERE `entry` = -1509019;
UPDATE `script_texts` SET `content_loc4` =  '我的力量回来了！' WHERE `entry` = -1509020;
UPDATE `script_texts` SET `content_loc4` =  '不惜一切代价保卫城市！' WHERE `entry` = -1509021;
UPDATE `script_texts` SET `content_loc4` =  '城墙被攻破了！' WHERE `entry` = -1509022;
UPDATE `script_texts` SET `content_loc4` =  '进入守备位置，保卫城市。' WHERE `entry` = -1509023;
UPDATE `script_texts` SET `content_loc4` =  '入侵者只有死路一条。' WHERE `entry` = -1509024;
UPDATE `script_texts` SET `content_loc4` =  '沙漠，扬起你的沙砾，遮蔽太阳的光芒吧！' WHERE `entry` = -1509025;
UPDATE `script_texts` SET `content_loc4` =  '你被终结了。' WHERE `entry` = -1509026;
UPDATE `script_texts` SET `content_loc4` =  '我败了……' WHERE `entry` = -1509027;
UPDATE `script_texts` SET `content_loc4` =  '真的那么渴求一死吗？我很乐意成全你们！' WHERE `entry` = -1531000;
UPDATE `script_texts` SET `content_loc4` =  '战栗吧凡人！黑暗降临的时刻到来了！' WHERE `entry` = -1531001;
UPDATE `script_texts` SET `content_loc4` =  '颤抖吧！你的末日来临了！' WHERE `entry` = -1531002;
UPDATE `script_texts` SET `content_loc4` =  '你的死亡将成为同伴的榜样！' WHERE `entry` = -1531003;
UPDATE `script_texts` SET `content_loc4` =  '懦弱的废物，再血海里挣扎吧！' WHERE `entry` = -1531004;
UPDATE `script_texts` SET `content_loc4` =  '让死亡与尖叫响彻云霄吧！让恐惧与迷茫的交响诗开始演奏吧！' WHERE `entry` = -1531005;
UPDATE `script_texts` SET `content_loc4` =  '准备迎接上古之神的回归吧！' WHERE `entry` = -1531006;
UPDATE `script_texts` SET `content_loc4` =  '你们只是在拖延必然的命运！' WHERE `entry` = -1531007;
UPDATE `script_texts` SET `content_loc4` =  '你们玷污了这片神圣的土地，会因此受到惩罚的。' WHERE `entry` = -1531008;
UPDATE `script_texts` SET `content_loc4` =  '我宣判你死刑！' WHERE `entry` = -1531009;
UPDATE `script_texts` SET `content_loc4` =  '我战斗到了最后一刻！' WHERE `entry` = -1531010;
UPDATE `script_texts` SET `content_loc4` =  '现在才想到逃跑？太迟了。' WHERE `entry` = -1531019;
UPDATE `script_texts` SET `content_loc4` =  '准备迎接毁灭的来临吧！' WHERE `entry` = -1531020;
UPDATE `script_texts` SET `content_loc4` =  '就像是飞蛾扑火。' WHERE `entry` = -1531021;
UPDATE `script_texts` SET `content_loc4` =  '你的狂妄无礼！' WHERE `entry` = -1531022;
UPDATE `script_texts` SET `content_loc4` =  '你逃不掉死亡的命运！ ' WHERE `entry` = -1531023;
UPDATE `script_texts` SET `content_loc4` =  '哥哥，不！' WHERE `entry` = -1531024;
UPDATE `script_texts` SET `content_loc4` =  '用它涂满我们的屋子吧！' WHERE `entry` = -1531025;
UPDATE `script_texts` SET `content_loc4` =  '啊，羊入虎口！' WHERE `entry` = -1531026;
UPDATE `script_texts` SET `content_loc4` =  '没人可以活着离开这里！' WHERE `entry` = -1531027;
UPDATE `script_texts` SET `content_loc4` =  '弟弟，快来，我们可以畅饮鲜血了！' WHERE `entry` = -1531028;
UPDATE `script_texts` SET `content_loc4` =  '看，弟弟，新鲜的血！' WHERE `entry` = -1531029;
UPDATE `script_texts` SET `content_loc4` =  '认命吧！' WHERE `entry` = -1531030;
UPDATE `script_texts` SET `content_loc4` =  '维克洛尔，我感觉到了你的痛苦！' WHERE `entry` = -1531031;
UPDATE `script_texts` SET `content_loc4` =  '将给你带来毁灭！' WHERE `entry` = -1531032;
UPDATE `script_texts` SET `content_loc4` =  '死亡，离你不远了。' WHERE `entry` = -1531033;
UPDATE `script_texts` SET `content_loc4` =  ' 你，已经死了。' WHERE `entry` = -1531034;
UPDATE `script_texts` SET `content_loc4` =  '你的勇气，已经消失殆尽。' WHERE `entry` = -1531035;
UPDATE `script_texts` SET `content_loc4` =  '你会被朋友们抛弃。' WHERE `entry` = -1531036;
UPDATE `script_texts` SET `content_loc4` =  '你会背叛你的朋友。' WHERE `entry` = -1531037;
UPDATE `script_texts` SET `content_loc4` =  '你会死。' WHERE `entry` = -1531038;
UPDATE `script_texts` SET `content_loc4` =  '你太软弱了。' WHERE `entry` = -1531039;
UPDATE `script_texts` SET `content_loc4` =  '你的心脏就要爆炸了。' WHERE `entry` = -1531040;
UPDATE `script_texts` SET `content_loc4` =  '啊......欢迎来到我的大厅！' WHERE `entry` = -1533000;
UPDATE `script_texts` SET `content_loc4` =  '一些小点心......' WHERE `entry` = -1533001;
UPDATE `script_texts` SET `content_loc4` =  '你们逃不掉的。' WHERE `entry` = -1533002;
UPDATE `script_texts` SET `content_loc4` =  '对，跑吧，那样伤口出血就更多啦！' WHERE `entry` = -1533003;
UPDATE `script_texts` SET `content_loc4` =  '啊，我听见一些可爱的小心脏在跳着。啊，跳得更快啦。不过，马上就都要停止了。' WHERE `entry` = -1533004;
UPDATE `script_texts` SET `content_loc4` =  ' 去哪里？做什么？太多的选择。可这一切都将在痛苦与死亡中终结。' WHERE `entry` = -1533005;
UPDATE `script_texts` SET `content_loc4` =  '我该先吃谁呢？真是难以选择。每一个闻起来都这么鲜美。' WHERE `entry` = -1533006;
UPDATE `script_texts` SET `content_loc4` =  '哦......小点心终于来了。我好久都没有吃肉和饮用鲜血了。' WHERE `entry` = -1533007;
UPDATE `script_texts` SET `content_loc4` =  '嘘......很快，一切就都结束了。' WHERE `entry` = -1533008;
UPDATE `script_texts` SET `content_loc4` =  '你们这些凡人，你们的意志一无是处。现在，你们都将成为主人的奴仆，并忠诚地为主人服务。世上最光荣的事，莫过于为主人的事业而牺牲。' WHERE `entry` = -1533009;
UPDATE `script_texts` SET `content_loc4` =  '以主人之名，杀了他们！' WHERE `entry` = -1533010;
UPDATE `script_texts` SET `content_loc4` =  '你休想从我面前逃掉！' WHERE `entry` = -1533011;
UPDATE `script_texts` SET `content_loc4` =  '跪下求饶吧，懦夫！' WHERE `entry` = -1533012;
UPDATE `script_texts` SET `content_loc4` =  '逃啊，有本事就逃啊！' WHERE `entry` = -1533013;
UPDATE `script_texts` SET `content_loc4` =  '你败了！' WHERE `entry` = -1533014;
UPDATE `script_texts` SET `content_loc4` =  '可怜虫！' WHERE `entry` = -1533015;
UPDATE `script_texts` SET `content_loc4` =  '主人......会为我复仇雪耻的！' WHERE `entry` = -1533016;
UPDATE `script_texts` SET `content_loc4` =  '帕奇维克要跟你玩！' WHERE `entry` = -1533017;
UPDATE `script_texts` SET `content_loc4` =  '帕奇维克是克尔苏加德的战神！' WHERE `entry` = -1533018;
UPDATE `script_texts` SET `content_loc4` =  '不玩了?' WHERE `entry` = -1533019;
UPDATE `script_texts` SET `content_loc4` =  '怎么……搞的……？' WHERE `entry` = -1533020;
UPDATE `script_texts` SET `content_loc4` =  '%s变得狂暴盛怒了!' WHERE `entry` = -1533021;
UPDATE `script_texts` SET `content_loc4` =  '%s暴怒了起来!' WHERE `entry` = -1533022;
UPDATE `script_texts` SET `content_loc4` =  '斯塔拉格要碾碎你！ ' WHERE `entry` = -1533023;
UPDATE `script_texts` SET `content_loc4` =  '斯塔拉格……宰了你！' WHERE `entry` = -1533024;
UPDATE `script_texts` SET `content_loc4` =  '主人……救救我…… ' WHERE `entry` = -1533025;
UPDATE `script_texts` SET `content_loc4` =  '主人要吃了你！' WHERE `entry` = -1533026;
UPDATE `script_texts` SET `content_loc4` =  '费尔根……要让主人高兴！' WHERE `entry` = -1533027;
UPDATE `script_texts` SET `content_loc4` =  '费尔根……完啦……' WHERE `entry` = -1533028;
UPDATE `script_texts` SET `content_loc4` =  '你们太迟了，我……只有服从！' WHERE `entry` = -1533029;
UPDATE `script_texts` SET `content_loc4` =  '杀！' WHERE `entry` = -1533030;
UPDATE `script_texts` SET `content_loc4` =  '咬碎你的骨头！' WHERE `entry` = -1533031;
UPDATE `script_texts` SET `content_loc4` =  '打烂你！' WHERE `entry` = -1533032;
UPDATE `script_texts` SET `content_loc4` =  '你死了！' WHERE `entry` = -1533033;
UPDATE `script_texts` SET `content_loc4` =  '你感受到痛苦的滋味儿了吧。' WHERE `entry` = -1533034;
UPDATE `script_texts` SET `content_loc4` =  '谢谢你！' WHERE `entry` = -1533035;
UPDATE `script_texts` SET `content_loc4` =  '求求你！' WHERE `entry` = -1533036;
UPDATE `script_texts` SET `content_loc4` =  '停下！停下这东西 ' WHERE `entry` = -1533037;
UPDATE `script_texts` SET `content_loc4` =  '帮帮我！救救我！' WHERE `entry` = -1533038;
UPDATE `script_texts` SET `content_loc4` =  '不！' WHERE `entry` = -1533039;
UPDATE `script_texts` SET `content_loc4` =  '你们这些蠢货已经主动步入了陷阱，你们正在挑战一个无比强大的存在！虽然你们经历了千难万险，才来到收割者的领域，来到了我的面前……但是现在，活下来的唯一途径，就是加入诅咒神教！' WHERE `entry` = -1533040;
UPDATE `script_texts` SET `content_loc4` =  '死亡是唯一的解脱方式!' WHERE `entry` = -1533041;
UPDATE `script_texts` SET `content_loc4` =  '啊……我还……事业未尽……' WHERE `entry` = -1533042;
UPDATE `script_texts` SET `content_loc4` =  '我已经等待很久了。现在你们将面对灵魂的收割者。' WHERE `entry` = -1533043;
UPDATE `script_texts` SET `content_loc4` =  '准备接招吧！' WHERE `entry` = -1533044;
UPDATE `script_texts` SET `content_loc4` =  '嘿，瑟里耶克，别把他们赶跑了，等我们玩够了再说。' WHERE `entry` = -1533045;
UPDATE `script_texts` SET `content_loc4` =  '真希望他们能撑久点，至少让我做完...自我介绍' WHERE `entry` = -1533046;
UPDATE `script_texts` SET `content_loc4` =  '肯定是我首开纪录，有人敢打赌吗？' WHERE `entry` = -1533047;
UPDATE `script_texts` SET `content_loc4` =  '你的命是我的了！' WHERE `entry` = -1533048;
UPDATE `script_texts` SET `content_loc4` =  '还有谁？' WHERE `entry` = -1533049;
UPDATE `script_texts` SET `content_loc4` =  '算你……厉害……' WHERE `entry` = -1533050;
UPDATE `script_texts` SET `content_loc4` =  '来啊，放马过来啊。' WHERE `entry` = -1533051;
UPDATE `script_texts` SET `content_loc4` =  '来吧，你们这群杂碎，我们可有四个人啊。' WHERE `entry` = -1533052;
UPDATE `script_texts` SET `content_loc4` =  '哭哭闹闹，没完没了。我都听烦了！你们要是不能闭上嘴，我来帮你们！ ' WHERE `entry` = -1533053;
UPDATE `script_texts` SET `content_loc4` =  '我要好好享受一下，把你们这群傻瓜蛋杀光的感觉。' WHERE `entry` = -1533054;
UPDATE `script_texts` SET `content_loc4` =  '我最喜欢烤肉啦！' WHERE `entry` = -1533055;
UPDATE `script_texts` SET `content_loc4` =  '下次，劳驾多带些朋友来。' WHERE `entry` = -1533056;
UPDATE `script_texts` SET `content_loc4` =  '喔，又要血流成河了。' WHERE `entry` = -1533057;
UPDATE `script_texts` SET `content_loc4` =  '逃走吧，否则就太迟了!' WHERE `entry` = -1533058;
UPDATE `script_texts` SET `content_loc4` =  '入侵者，立刻结束这无谓的冒险!趁你们还活着，马上离开这里！' WHERE `entry` = -1533059;
UPDATE `script_texts` SET `content_loc4` =  '或许……他们会觉悟过来，然后立刻逃离这里。' WHERE `entry` = -1533060;
UPDATE `script_texts` SET `content_loc4` =  '不要继续了！趁还有时间快撤退！' WHERE `entry` = -1533061;
UPDATE `script_texts` SET `content_loc4` =  '除了服从，我别无选择!' WHERE `entry` = -1533062;
UPDATE `script_texts` SET `content_loc4` =  '原谅我！' WHERE `entry` = -1533063;
UPDATE `script_texts` SET `content_loc4` =  '这就是……必然的归宿' WHERE `entry` = -1533064;
UPDATE `script_texts` SET `content_loc4` =  '你去死吧！' WHERE `entry` = -1533065;
UPDATE `script_texts` SET `content_loc4` =  '休想过去！' WHERE `entry` = -1533066;
UPDATE `script_texts` SET `content_loc4` =  '不许动！' WHERE `entry` = -1533067;
UPDATE `script_texts` SET `content_loc4` =  '你死后，也永远不得安宁……' WHERE `entry` = -1533068;
UPDATE `script_texts` SET `content_loc4` =  '这是主人的意志……' WHERE `entry` = -1533069;
UPDATE `script_texts` SET `content_loc4` =  '臣服于大领主的力量吧！' WHERE `entry` = -1533070;
UPDATE `script_texts` SET `content_loc4` =  '别多说废话啦，让他们来吧，我们会把他们的骨头，碾成灰的。' WHERE `entry` = -1533071;
UPDATE `script_texts` SET `content_loc4` =  '保留你的愤懑，压抑你的怒火吧！很快，你们就只能体会到挫折感了。' WHERE `entry` = -1533072;
UPDATE `script_texts` SET `content_loc4` =  '生命本身毫无意义，只有死亡，才能让你了解人性的真谛。' WHERE `entry` = -1533073;
UPDATE `script_texts` SET `content_loc4` =  '我……自由啦……希望还不是太迟，圣光啊！请再多给我一些……时间…… ' WHERE `entry` = -1533074;
UPDATE `script_texts` SET `content_loc4` =  '荣耀归于我主。' WHERE `entry` = -1533075;
UPDATE `script_texts` SET `content_loc4` =  '我要没收你的生命！' WHERE `entry` = -1533076;
UPDATE `script_texts` SET `content_loc4` =  '死吧，入侵者！ ' WHERE `entry` = -1533077;
UPDATE `script_texts` SET `content_loc4` =  '起来吧我的战士们！起来，再为主人尽忠一次！ ' WHERE `entry` = -1533078;
UPDATE `script_texts` SET `content_loc4` =  '任务完结。' WHERE `entry` = -1533079;
UPDATE `script_texts` SET `content_loc4` =  '终止你的呼吸吧。' WHERE `entry` = -1533080;
UPDATE `script_texts` SET `content_loc4` =  '我要侍奉主人……到……最后一刻。' WHERE `entry` = -1533081;
UPDATE `script_texts` SET `content_loc4` =  '一切都在按照计划进行，主人。' WHERE `entry` = -1533084;
UPDATE `script_texts` SET `content_loc4` =  '你们对我如此忠诚这很好，很快，世间的一切生物都将只为巫妖王效命。你们都会得到奖赏的——只要你们不让我失望……' WHERE `entry` = -1533085;
UPDATE `script_texts` SET `content_loc4` =  '我可以预见战事的发展将……等等！怎么回事？！' WHERE `entry` = -1533086;
UPDATE `script_texts` SET `content_loc4` =  '你的防御体系已经被攻破啦！马上去把这些入侵者解决掉！' WHERE `entry` = -1533087;
UPDATE `script_texts` SET `content_loc4` =  '遵命，主人！' WHERE `entry` = -1533088;
UPDATE `script_texts` SET `content_loc4` =  '不！你被诅咒了，闯入者！巫妖王的军队会杀了你的，你逃不出命运的。' WHERE `entry` = -1533089;
UPDATE `script_texts` SET `content_loc4` =  '谁敢入侵我的神圣领域？我警告你们：曾有许多蠢货入侵这里——他们都已经死啦！' WHERE `entry` = -1533090;
UPDATE `script_texts` SET `content_loc4` =  '蠢货！你们以为胜券在握了吗？你们只是离地狱更近了一步而以！' WHERE `entry` = -1533091;
UPDATE `script_texts` SET `content_loc4` =  '这场游戏已经让我觉得无聊啦。继续吧，到我这里来，我会亲自毁灭你们的灵魂！' WHERE `entry` = -1533092;
UPDATE `script_texts` SET `content_loc4` =  '看来你们还不知道自己将面临怎样的恐怖，看来你们还一无所知——纳克萨玛斯的霜寒之心，正等待着你们！' WHERE `entry` = -1533093;
UPDATE `script_texts` SET `content_loc4` =  '祈祷我的慈悲吧！' WHERE `entry` = -1533094;
UPDATE `script_texts` SET `content_loc4` =  '呼出你的最后一口气！' WHERE `entry` = -1533095;
UPDATE `script_texts` SET `content_loc4` =  '你的末日临近啦！' WHERE `entry` = -1533096;
UPDATE `script_texts` SET `content_loc4` =  '黑暗的虚空，正等着你哪！' WHERE `entry` = -1533097;
UPDATE `script_texts` SET `content_loc4` =  '<Kel\'Thuzad cackles maniacally!>' WHERE `entry` = -1533098;
UPDATE `script_texts` SET `content_loc4` =  '噢啊！……没这么容易……你们的胜利空洞而虚无，没有任何意义，我很快就将卷土重来！' WHERE `entry` = -1533099;
UPDATE `script_texts` SET `content_loc4` =  '你的灵魂现在属于我！' WHERE `entry` = -1533100;
UPDATE `script_texts` SET `content_loc4` =  '没有人能逃掉！' WHERE `entry` = -1533101;
UPDATE `script_texts` SET `content_loc4` =  '我要冻结你的每一滴血。' WHERE `entry` = -1533102;
UPDATE `script_texts` SET `content_loc4` =  '主人，我需要帮助！' WHERE `entry` = -1533103;
UPDATE `script_texts` SET `content_loc4` =  '很好，冰荒废土的战士们，起来吧，我命令你们为主人而战斗 、杀戮，直到死亡……一个活口都不要留！' WHERE `entry` = -1533104;
UPDATE `script_texts` SET `content_loc4` =  '仆从们！侍卫们！隶属于黑暗和寒冷的战士们！听从克尔苏加德的召唤！' WHERE `entry` = -1533105;
UPDATE `script_texts` SET `content_loc4` =  '你们可笑的魔法对天灾军团来说不值一提！' WHERE `entry` = -1533106;
UPDATE `script_texts` SET `content_loc4` =  '够啦，我对这些杂耍已经感到厌烦啦！' WHERE `entry` = -1533107;
UPDATE `script_texts` SET `content_loc4` =  '蠢货，你们简直是太弱啦！出来吧，我的奴仆！' WHERE `entry` = -1533108;
UPDATE `script_texts` SET `content_loc4` =  '你是我的啦！' WHERE `entry` = -1533109;
UPDATE `script_texts` SET `content_loc4` =  '我看到你了……' WHERE `entry` = -1533110;
UPDATE `script_texts` SET `content_loc4` =  '你……就是下一个！' WHERE `entry` = -1533111;
UPDATE `script_texts` SET `content_loc4` =  '闭上双眼，长眠吧！' WHERE `entry` = -1533112;
UPDATE `script_texts` SET `content_loc4` =  '世间的一切种族终将灭绝，这是迟早的事情。' WHERE `entry` = -1533113;
UPDATE `script_texts` SET `content_loc4` =  '我看我看到了无尽的苦难，我看到无穷的折磨，我看见了滔天的愤怒——我，看到了一切…… ' WHERE `entry` = -1533114;
UPDATE `script_texts` SET `content_loc4` =  '很快，这个世界将开始颤抖！' WHERE `entry` = -1533115;
UPDATE `script_texts` SET `content_loc4` =  '你的生命，正走向终结。' WHERE `entry` = -1533116;
UPDATE `script_texts` SET `content_loc4` =  '饥饿的蠕虫，将要吞噬你腐烂的躯体。' WHERE `entry` = -1533117;
UPDATE `script_texts` SET `content_loc4` =  '不... 不...' WHERE `entry` = -1533118;
UPDATE `script_texts` SET `content_loc4` =  '哈哈，我正好刚刚热完身。' WHERE `entry` = -1533120;
UPDATE `script_texts` SET `content_loc4` =  '来吧！' WHERE `entry` = -1533121;
UPDATE `script_texts` SET `content_loc4` =  '让我看看你有什么能耐！' WHERE `entry` = -1533122;
UPDATE `script_texts` SET `content_loc4` =  '绊腿……有什么问题吗？' WHERE `entry` = -1533123;
UPDATE `script_texts` SET `content_loc4` =  '你该在家里呆着！' WHERE `entry` = -1533124;
UPDATE `script_texts` SET `content_loc4` =  '按我的教导去做！' WHERE `entry` = -1533125;
UPDATE `script_texts` SET `content_loc4` =  '仁慈无用！' WHERE `entry` = -1533126;
UPDATE `script_texts` SET `content_loc4` =  '你们太令我失望了，学生们！' WHERE `entry` = -1533127;
UPDATE `script_texts` SET `content_loc4` =  '练习时间到此为止！都拿出真本事来！' WHERE `entry` = -1533128;
UPDATE `script_texts` SET `content_loc4` =  '光荣的……战死……' WHERE `entry` = -1533129;
